/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.models;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import main.dao.connexion;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;

/**
 *
 * @author HP
 */
public class FrameAuthentification extends javax.swing.JFrame {
private Animator animatorLogin;
    private Animator animatorBody;
    private boolean signIn;
    /**
     * Creates new form FrameAuthentification
     */
    public FrameAuthentification() {
        initComponents();
       
        setBackground(new Color(0,0,0));
         init();

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
                         

    private void cmdSignInActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
            
       init(); 
    }
private void init(){
    header1.initMoving(this);
    header1.initEvent(this,borderPane1);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        borderPane1 = new main.swing.BorderPane();
        header1 = new main.compenent.header();
        backgroundlogin1 = new main.swing.Backgroundlogin();
        txtUser = new main.swing.Textfiliedsingin();
        txtPass = new main.swing.Passwordlogin();
        buttonsingin1 = new main.swing.Buttonsingin();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        borderPane1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout backgroundlogin1Layout = new javax.swing.GroupLayout(backgroundlogin1);
        backgroundlogin1.setLayout(backgroundlogin1Layout);
        backgroundlogin1Layout.setHorizontalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        backgroundlogin1Layout.setVerticalGroup(
            backgroundlogin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        txtUser.setBackground(new java.awt.Color(0, 0, 0));
        txtUser.setForeground(new java.awt.Color(255, 51, 255));
        txtUser.setFont(new java.awt.Font("Yu Gothic", 2, 13)); // NOI18N
        txtUser.setLabelText("Username ...");
        txtUser.setOpaque(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        txtPass.setBackground(new java.awt.Color(0, 0, 0));
        txtPass.setForeground(new java.awt.Color(255, 51, 255));
        txtPass.setFont(new java.awt.Font("Yu Gothic", 2, 13)); // NOI18N
        txtPass.setLabelText("Password...");
        txtPass.setOpaque(false);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        buttonsingin1.setBackground(new java.awt.Color(102, 102, 255));
        buttonsingin1.setForeground(new java.awt.Color(255, 255, 255));
        buttonsingin1.setText("LOG IN");
        buttonsingin1.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        buttonsingin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonsingin1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setText("Connexion");

        javax.swing.GroupLayout borderPane1Layout = new javax.swing.GroupLayout(borderPane1);
        borderPane1.setLayout(borderPane1Layout);
        borderPane1Layout.setHorizontalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundlogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(borderPane1Layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addGroup(borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, borderPane1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(buttonsingin1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(496, Short.MAX_VALUE))
        );
        borderPane1Layout.setVerticalGroup(
            borderPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borderPane1Layout.createSequentialGroup()
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonsingin1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(backgroundlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(borderPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsingin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonsingin1ActionPerformed
        // TODO add your handling code here:
       String username= txtUser.getText();
       String mdp= txtPass.getText();
       if(!username.equals("") && !mdp.equals("") ){
           try {
               String req="select * from login where username=? and mdp=?";
               Connection con= connexion.seConnecter();
               PreparedStatement ps=con.prepareStatement(req);
               ps.setString(1,username);
               ps.setString(2,mdp);
               ResultSet rs=ps.executeQuery();
               if(rs.next()){
                   new Main().setVisible(true);
               dispose();
               }else{
                   JOptionPane.showMessageDialog(null, "Login /mdp invalide");
                 
               }
               rs.close();
               con.close();
               
           } catch (Exception ex) {
               Logger.getLogger(FrameAuthentification.class.getName()).log(Level.SEVERE, null, ex);
           }
       
       }  else  {
           txtUser.setHelperText("Please input user name");
           txtPass.setHelperText("Please input password");
       }
            
            
        
    }//GEN-LAST:event_buttonsingin1ActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAuthentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAuthentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.swing.Backgroundlogin backgroundlogin1;
    private main.swing.BorderPane borderPane1;
    private main.swing.Buttonsingin buttonsingin1;
    private main.compenent.header header1;
    private javax.swing.JLabel jLabel1;
    private main.swing.Passwordlogin txtPass;
    private main.swing.Textfiliedsingin txtUser;
    // End of variables declaration//GEN-END:variables
}
