/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.models.form;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import main.chart.ModelChart;
import main.dao.connexion;
import main.swing.Model.Model_Card;

/**
 *
 * @author HP
 */
public class Dashnoard extends javax.swing.JPanel {

    /**
     * Creates new form Dashnoard
     */
    public Dashnoard() {
        initComponents();
         testData();
    }
 private void testData() {
        try {
            Connection  con=connexion.seConnecter();
            Statement s=con.createStatement();
            float couttotal=0;
            float budgettotal=0;
            float profit=0;
            ResultSet re= s.executeQuery("select  sum(cout_total) from Formation join Plan_formation using(Code_formation)");
            if(re.next()){
                
                couttotal=re.getFloat(1);
               
            }
            budgettotal=(float) (couttotal*0.92);
            profit=couttotal-budgettotal;
            re.close();
            card1.setData(new Model_Card(new ImageIcon(getClass().getResource("/main/icons/icons8_transaction_48px.png")), " Revenu annuel", "$ "+couttotal));
            card2.setData(new Model_Card(new ImageIcon(getClass().getResource("/main/icons/icons8_receive_euro_64px.png")), "Budget Total", "$ "+budgettotal));
            card3.setData(new Model_Card(new ImageIcon(getClass().getResource("/main/icons/icons8_general_ledger_48px.png")), "Profit", "$ "+profit));
            chartAnimation1.addLegend(" Revenu annuel", new Color(245, 189, 135));
            chartAnimation1.addLegend("Budget Total", new Color(135, 189, 245));
            chartAnimation1.addLegend("Profit", new Color(189, 135, 245));
            
        double[] tab= new double[3];
         double[] tab2= new double[3];
          double[] tab3= new double[3];
           double[] tab4= new double[3];
            double[] tab5= new double[3];
             double[] tab6= new double[3];
       
         re= s.executeQuery(" select sum( decode(to_char(Date_debut,'mm'),01,sum(cout_total),0)) as Jan, sum(decode(to_char(Date_debut,'mm'),02,sum(cout_total),0)) as feb, sum( decode(to_char(Date_debut,'mm'),03,sum(cout_total),0)) as mar, sum( decode(to_char(Date_debut,'mm'),04,sum(cout_total),0)) as apr, sum( decode(to_char(Date_debut,'mm'),05,sum(cout_total),0)) as may, sum( decode(to_char(Date_debut,'mm'),06,sum(cout_total),0)) as jui from Plan_formation join Formation using (Code_formation) where to_char(date_debut,'yyyy') like 2022 group by date_debut  ");
            int i=0;
       while(re.next()){
       
            tab[0]=re.getDouble(1);
            tab[1]=re.getDouble(1)*0.92;
            tab[2]=re.getDouble(1)*0.08;
             tab2[0]=re.getDouble(2);
            tab2[1]=re.getDouble(2)*0.92;
            tab2[2]=re.getDouble(2)*0.08;
            tab3[0]=re.getDouble(3);
            tab3[1]=re.getDouble(3)*0.92;
            tab3[2]=re.getDouble(3)*0.08;
             tab4[0]=re.getDouble(4);
            tab4[1]=re.getDouble(4)*0.92;
            tab5[2]=re.getDouble(4)*0.08;
            tab5[0]=re.getDouble(5);
            tab5[1]=re.getDouble(5)*0.92;
            tab6[2]=re.getDouble(5)*0.08;
             tab6[0]=re.getDouble(6);
            tab6[1]=re.getDouble(6)*0.92;
            tab6[2]=re.getDouble(6)*0.08;
        
        }re.close();
            chartAnimation1.addData(new ModelChart("January", tab));
            chartAnimation1.addData(new ModelChart("February", tab2));
            chartAnimation1.addData(new ModelChart("March",tab3));
            chartAnimation1.addData(new ModelChart("April", tab4));
            chartAnimation1.addData(new ModelChart("May", tab5));
            chartAnimation1.addData(new ModelChart("June", tab6));
            chartAnimation1.start();
        } catch (Exception ex) {
            Logger.getLogger(Dashnoard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        card1 = new main.compenent.Card();
        card2 = new main.compenent.Card();
        card3 = new main.compenent.Card();
        panelShadow1 = new main.swing.PanelShadow();
        chartAnimation1 = new main.chart.ChartAnimation();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 110, 207));
        jLabel1.setText("Dashboard");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        panelShadow1.setBackground(new java.awt.Color(204, 204, 204));

        chartAnimation1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 110, 207));
        jLabel2.setText("Chart Report");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        javax.swing.GroupLayout panelShadow1Layout = new javax.swing.GroupLayout(panelShadow1);
        panelShadow1.setLayout(panelShadow1Layout);
        panelShadow1Layout.setHorizontalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelShadow1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(chartAnimation1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelShadow1Layout.setVerticalGroup(
            panelShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelShadow1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(chartAnimation1, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(card1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(card2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(card3, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                    .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(card1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(card3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(panelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.compenent.Card card1;
    private main.compenent.Card card2;
    private main.compenent.Card card3;
    private main.chart.ChartAnimation chartAnimation1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private main.swing.PanelShadow panelShadow1;
    // End of variables declaration//GEN-END:variables
}
